# Generated by Django 4.2.3 on 2025-01-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('business_form', models.CharField(max_length=10)),
                ('reg_number', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=25)),
            ],
        ),
    ]
