# Generated by Django 4.2.3 on 2025-02-17 09:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import bills.validations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_nr', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')])),
                ('area', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')])),
                ('wm_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')])),
                ('hm_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')])),
                ('person_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')])),
                ('contract_nr', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, 'Must be at least 5 characters')])),
                ('e_mail', models.EmailField(max_length=254)),
                ('billing_address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, 'Must be at least 5 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(6, 'Must be at least 6 characters'), django.core.validators.MaxLengthValidator(50, 'Max length is 50 characters')])),
                ('apartment_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')])),
                ('area_of_apartments_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')])),
                ('area_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')])),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='account',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(10, 'Must be at least 10 characters'), django.core.validators.MaxLengthValidator(25, 'Max length is 25 characters'), bills.validations.valid_bank_account]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='business_form',
            field=models.CharField(choices=[('SIA', 'SIA'), ('SIA', 'AS'), ('IU', 'IU'), ('SDV', 'SDV')], max_length=15),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 characters'), django.core.validators.MaxLengthValidator(50, 'Max length is 50 characters'), bills.validations.valid_provider_name]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='reg_number',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(11, 'Must be at least 11 characters'), django.core.validators.MaxLengthValidator(25, 'Max length is 25 characters'), bills.validations.valid_reg_number]),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'Must be at least 3 characters')])),
                ('service_type', models.CharField(choices=[('public', 'Public'), ('individual', 'Individual')], max_length=10)),
                ('measuring_units', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(1, 'Must be at least 1 character')])),
                ('meters_of_volume', models.BooleanField(choices=[(True, 'With Meters'), (False, 'No Meters')], default=True)),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bills.house')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cold water', 'cold'), ('Hot water', 'hot'), ('Heat', 'heat'), ('Other', 'other')], max_length=10)),
                ('manufacturer', models.CharField(default=' ', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 characters')])),
                ('series', models.CharField(default=' ', max_length=5)),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 digits'), bills.validations.valid_meter_nr])),
                ('reading_default', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')])),
                ('verification_date', models.DateField(default=datetime.date.today, verbose_name='Verification date')),
                ('address', models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='bills.house')),
                ('apartment_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.house'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='consumer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='bills.consumer'),
        ),
    ]
