# Generated by Django 4.2.3 on 2025-01-30 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_apartment_house_service_alter_provider_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='area_of_apartments_total',
            field=models.IntegerField(default=999, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')]),
        ),
        migrations.AddField(
            model_name='house',
            name='area_total',
            field=models.IntegerField(default=999, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')]),
        ),
    ]
