# Generated by Django 4.2.3 on 2025-02-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_apartment_consumer_house_alter_provider_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='address',
        ),
    ]
