# Generated by Django 4.2.3 on 2025-01-30 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_house_area_of_apartments_total_house_area_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='area_of_apartments_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')]),
        ),
        migrations.AlterField(
            model_name='house',
            name='area_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')]),
        ),
    ]
