# Generated by Django 4.2.3 on 2025-01-30 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_house_area_of_apartments_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='verification_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
