# Generated by Django 4.2.3 on 2025-01-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_alter_meter_verification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='address',
        ),
    ]
