# Generated by Django 4.2.3 on 2025-02-02 13:15

import bills.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_remove_consumer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='house',
            field=models.ManyToManyField(related_name='house', related_query_name='house', to='bills.house'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 characters'), django.core.validators.MaxLengthValidator(50, 'Max length is 50 characters'), bills.validations.valid_provider_name]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='reg_number',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(11, 'Must be at least 11 characters'), django.core.validators.MaxLengthValidator(25, 'Max length is 25 characters'), bills.validations.valid_reg_number]),
        ),
    ]
