# Generated by Django 4.2.3 on 2025-02-03 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_service_house_alter_provider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='manufacturer',
            field=models.CharField(default=' ', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 characters')]),
        ),
        migrations.AddField(
            model_name='meter',
            name='series',
            field=models.CharField(default=' ', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 characters')]),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(6, 'Must be at least 6 characters'), django.core.validators.MaxLengthValidator(50, 'Max length is 50 characters')]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='business_form',
            field=models.CharField(choices=[('sia', 'SIA'), ('as', 'AS'), ('iu', 'IU'), ('sdv', 'SDV')], max_length=15),
        ),
    ]
