# Generated by Django 4.2.3 on 2025-02-04 09:34

import bills.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_meter_manufacturer_meter_series_alter_house_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 characters'), bills.validations.valid_meter_nr]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='account',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(10, 'Must be at least 10 characters'), django.core.validators.MaxLengthValidator(25, 'Max length is 25 characters'), bills.validations.valid_bank_account]),
        ),
    ]
