# Generated by Django 4.2.3 on 2025-02-08 10:42

import bills.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_alter_meter_number_alter_provider_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='houseLocation',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='meter',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 digits'), bills.validations.valid_meter_nr]),
        ),
        migrations.AlterField(
            model_name='meter',
            name='series',
            field=models.CharField(default=' ', max_length=5),
        ),
    ]
