# Generated by Django 4.2.3 on 2025-02-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_remove_meter_address'),
        ('bills', '0010_rename_houselocation_apartment_address_and_more'),
    ]

    operations = [
    ]
