# Generated by Django 4.2.3 on 2025-02-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_merge_20250217_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='address',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='bills.house'),
        ),
    ]
