# Generated by Django 4.2.3 on 2025-02-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_meter_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='address',
        ),
    ]
