# Generated by Django 4.2.3 on 2025-02-24 09:55

import bills.validations
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_meter_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='wm_count',
        ),
        migrations.AddField(
            model_name='apartment',
            name='cold_wm_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of cold water meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='hot_wm_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of hot water meters'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')], verbose_name='Area of apartment'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='hm_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of heat meters'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='person_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of persons'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.house', verbose_name='House address'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='apartment_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='bills.apartment', verbose_name='Apartment number'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='manufacturer',
            field=models.CharField(default=' ', max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 characters')], verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 digits'), bills.validations.valid_meter_nr], verbose_name='Meter number'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='reading_default',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Default reading (on installation)'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='series',
            field=models.CharField(default=' ', max_length=5, verbose_name='Series (if applicable)'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='type',
            field=models.CharField(choices=[('cold', 'Cold water'), ('electricity', 'Electricity'), ('hot', 'Hot water'), ('heat', 'Heat'), ('other', 'Other')], max_length=15, verbose_name='Type of meter'),
        ),
    ]
