# Generated by Django 4.2.3 on 2025-02-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0015_remove_apartment_wm_count_apartment_cold_wm_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='cold_wm_count',
            new_name='cold_meters_count',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='hm_count',
            new_name='heat_meters_count',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='hot_wm_count',
            new_name='hot_meters_count',
        ),
    ]
