# Generated by Django 4.2.3 on 2025-02-25 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0016_rename_cold_wm_count_apartment_cold_meters_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Format: YYYY', validators=[django.core.validators.RegexValidator('^(202[1-9]|20[3-9])$')])),
                ('month', models.PositiveSmallIntegerField(help_text='Format: YYYY', validators=[django.core.validators.RegexValidator('^(0?[1-9]|1[0-2])$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.service')),
            ],
        ),
    ]
