# Generated by Django 4.2.3 on 2025-02-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0017_incomingbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingbill',
            name='house',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bills.house'),
            preserve_default=False,
        ),
    ]
