# Generated by Django 4.2.3 on 2025-03-03 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_incomingbill_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, 'Must be at least 5 characters')])),
                ('reg_number', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(11, 'Must be at least 11 characters')])),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, 'Must be at least 5 characters')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(11, 'Must be at least 11 characters')])),
                ('e_mail', models.EmailField(max_length=254)),
                ('account', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(10, 'Must be at least 10 characters')])),
            ],
        ),
        migrations.AlterField(
            model_name='incomingbill',
            name='month',
            field=models.PositiveSmallIntegerField(help_text='Format: MM', validators=[django.core.validators.RegexValidator('^(0?[1-9]|1[0-2])$')]),
        ),
        migrations.CreateModel(
            name='OutgoingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_nr', models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Must be at least 2 characters')])),
                ('year', models.PositiveIntegerField(help_text='Format: YYYY', validators=[django.core.validators.RegexValidator('^(202[1-9]|20[3-9])$')])),
                ('month', models.PositiveSmallIntegerField(help_text='Format: MM', validators=[django.core.validators.RegexValidator('^(0?[1-9]|1[0-2])$')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.apartment')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.consumer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.provider')),
            ],
        ),
    ]
