# Generated by Django 4.2.3 on 2025-03-03 10:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0019_housemanagement_alter_incomingbill_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingbill',
            name='provider',
        ),
        migrations.AddField(
            model_name='outgoingbill',
            name='house_management',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bills.housemanagement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingbill',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bills.service'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(default=datetime.date.today, verbose_name='Reading date')),
                ('default_reading_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Default reading value')),
                ('previous_reading_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Previous reading value')),
                ('current_reading_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Current reading value')),
                ('consumption', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Consumption')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.meter')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(verbose_name='Reading Date')),
                ('reading_value', models.DecimalField(decimal_places=3, help_text='Current meter reading value', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reading Value')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='bills.meter')),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
                'ordering': ['-reading_date', 'meter'],
                'indexes': [models.Index(fields=['reading_date', 'meter'], name='bills_meter_reading_0a5fbd_idx')],
                'unique_together': {('meter', 'reading_date')},
            },
        ),
    ]
