# Generated by Django 4.2.3 on 2025-03-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0020_remove_outgoingbill_provider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readings',
        ),
    ]
