# Generated by Django 4.2.3 on 2025-03-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0021_delete_readings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['-reading_date']},
        ),
        migrations.RemoveIndex(
            model_name='meterreading',
            name='bills_meter_reading_0a5fbd_idx',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.meter'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading_value',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
