# Generated by Django 4.2.3 on 2025-03-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0022_alter_meterreading_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingbill',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
