# Generated by Django 4.2.3 on 2025-03-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0023_incomingbill_quantity_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bills.provider'),
        ),
    ]
