# Generated by Django 4.2.3 on 2025-03-18 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0024_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='heated_area',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')], verbose_name='Heated area of apartment'),
        ),
        migrations.AddField(
            model_name='house',
            name='area_of_apartments_heated_total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('cold_water', 'Cold water'), ('electricity', 'Electricity'), ('hot_water', 'Hot water'), ('heat', 'Heat'), ('other', 'Other')], max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'Must be at least 3 characters')]),
        ),
    ]
