# Generated by Django 4.2.3 on 2025-03-18 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0025_apartment_heated_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='heated_area',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Must be at least 1')], verbose_name='Heated area of apartment'),
        ),
        migrations.AlterField(
            model_name='house',
            name='apartment_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')]),
        ),
        migrations.AlterField(
            model_name='house',
            name='area_of_apartments_heated_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Total heated area of apartments'),
        ),
    ]
