# Generated by Django 4.2.3 on 2025-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0026_alter_apartment_heated_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('object_count', 'Count of objects (524.4.1)'), ('part_of_house', 'Part of house (524.4.2)'), ('living_person_count', 'Count of living persons (524.4.3)'), ('declared_person_count', 'Count of declared persons (524.4.4)'), ('area', 'Area (524.17.1)')], max_length=30),
        ),
    ]
