# Generated by Django 4.2.3 on 2025-03-21 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0027_alter_service_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='person_count',
        ),
        migrations.AddField(
            model_name='apartment',
            name='declared_person_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of declared persons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='living_person_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of living persons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='declared_person_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of declared persons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='living_person_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of living persons'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('object_count', 'Count of objects (524.4.1)'), ('part_of_house', 'Part of house (524.4.2)'), ('living_person_count', 'Count of living persons (524.4.3)'), ('declared_person_count', 'Count of declared persons (524.4.4)'), ('area', 'Area (524.17.1)'), ('volume', 'Volume (524.17.2)')], max_length=30),
        ),
    ]
