# Generated by Django 4.2.3 on 2025-04-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0030_customposition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPosition',
        ),
    ]
