# Generated by Django 4.2.3 on 2025-04-02 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0031_delete_customposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingbill',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RenameField(
            model_name='outgoingbill',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='outgoingbill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingbill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='outgoingbill',
            unique_together={('apartment', 'year', 'month')},
        ),
        migrations.CreateModel(
            name='OutgoingBillPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('public', 'Public Service'), ('individual', 'Individual Service')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='bills.outgoingbill')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.meter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.service')),
            ],
            options={
                'ordering': ['position_type', 'service__name'],
            },
        ),
        migrations.RemoveField(
            model_name='outgoingbill',
            name='extra_fields',
        ),
        migrations.RemoveField(
            model_name='outgoingbill',
            name='service',
        ),
    ]
