# Generated by Django 4.2.3 on 2025-04-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0032_alter_outgoingbill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outgoingbill',
            options={},
        ),
        migrations.RenameField(
            model_name='outgoingbill',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.AlterUniqueTogether(
            name='outgoingbill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='outgoingbill',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='outgoingbill',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bills.service'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OutgoingBillPosition',
        ),
        migrations.RemoveField(
            model_name='outgoingbill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='outgoingbill',
            name='updated_at',
        ),
    ]
