# Generated by Django 4.2.3 on 2025-04-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0033_alter_outgoingbill_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cold', 'Cold water'), ('electricity', 'Electricity'), ('hot', 'Hot water'), ('heat', 'Heat'), ('other', 'Other')], max_length=15, verbose_name='Type of meter')),
                ('name', models.CharField(max_length=15, verbose_name='Name of meter')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('reading_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.housemeter')),
            ],
            options={
                'ordering': ['-reading_date'],
                'unique_together': {('house_meter', 'reading_date')},
            },
        ),
    ]
