# Generated by Django 4.2.3 on 2025-04-08 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0034_housemeter_housemeterreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='electricity_meters_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of electricity meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='gas_meters_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Can not be negative number')], verbose_name='Count of gas meters'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='heated_area',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Must be at least 0')], verbose_name='Heated area of apartment'),
        ),
    ]
