# Generated by Django 4.2.3 on 2025-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0036_apartment_mean_house_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='meters_of_volume',
        ),
        migrations.AddField(
            model_name='service',
            name='water_difference_calculation',
            field=models.CharField(choices=[('object_count', 'Object count'), ('last_month_consumption', 'Last month consumption'), ('last_3_months_consumption', 'Last 3 months consumption'), ('part_of_house', 'Part of house'), ('living_person_count', 'Living person count'), ('declared_person_count', 'Declared person count'), ('room_wo_person', 'Room without person')], default='object_count', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('object_count', 'Count of objects (524.4.1)'), ('part_of_house', 'Part of house (524.4.2)'), ('living_person_count', 'Count of living persons (524.4.3)'), ('declared_person_count', 'Count of declared persons (524.4.4)'), ('area', 'Area (524.17.1)'), ('heated_area', 'Heated area'), ('volume', 'Volume (524.17.2)'), ('one_time_payment', 'One time payment')], max_length=30),
        ),
    ]
